version: "3.7"

services:
  server:
    build: ./server
    environment:
      NODE_ENV:
      MONGO_URL: mongodb://mongo:27017/CCXGoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections'  && node db-reset.js && npm run start; do sleep 2; done"
    ports:
      - "4000:4000"

  # frontend:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server

  mongo:
    image: mongo:4.4
    user: mongodb
    expose:
      - 27017