version: "3.7"

services:
  server:
    build: ./server
    environment:
      NODE_ENV:
      MONGO_URL: mongodb://mongo:27017/CCXGoat
      PORT: 3001
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node index.js; do sleep 2; done"
    ports:
      - "3001:3001"

  frontend:
    build: ./app
    environment:
      REACT_APP_SERVER_URL: http://localhost:4000
    command: npm run start
    ports:
      - "80:80"
    depends_on:
      - server

  mongo:
    image: mongo:4.4
    user: mongodb
    expose:
      - 27017